### ISSUE TITLE
ImportError: cannot import name 'six'

### ISSUE THREAD

**Issue by realjumy** [springload/wagtailenforcer#19]
The Django 3.0.0 release notes specify that certain private Python 2 compatibility APIs were removed. Among those was `django.utils.six`. An alternative is required.

**Comment by G-kodes** [comment]
This is a breaking error. I can confirm I am experiencing it on my side as well:

```bash
Traceback (most recent call last):
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/nginx/html/SASDGHUB_Django/SASDGHUB/wsgi.py", line 25, in <module>
    application = get_wsgi_application()
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/nginx/html/SASDGHUB_Django/venv/lib64/python3.6/site-packages/axes/models.py", line 2, in <module>
    from django.utils import six
ImportError: cannot import name 'six'
```
